sudo: false
cache:
  directories:
  - node_modules
# KLUDGE: The following declarations are excluded by purpose. Our OSX boxes do not have NVM on them.
# SEE: ./scripts/travis/install.sh
# language: node_js
# node_js:
#  - "0.10"
os:
- osx
- linux
before_install:
- mkdir $HOME/.appgyver
- echo $APPGYVER_ACCESS_TOKEN_CONTENTS > $HOME/.appgyver/token.json
- echo $DEVGYVER_ACCESS_TOKEN_CONTENTS > $HOME/.appgyver/devgyver.richard.token.json
install:
- ./scripts/travis/install.sh
script:
- echo "script lol"
- STEROIDS_TEST_DEBUG=true ./bin/test release y
after_success:
- echo "after success lol --> $TRAVIS_TEST_RESULT"
after_failure:
- echo "after failure lol --> $TRAVIS_TEST_RESULT"
env:
- LONGCAT=looooong
deploy:
  provider: npm
  email: hostmaster+npm@appgyver.com
  api_key:
    secure: a5j/oPstEoYL3J/p01SmEUdHcmdrc1oQY1nDgf6DusPO5hyjk04R5BpRhYaIOcO2y8ujCFizEDmD0ToeEHXiwyv5fShqYdsiYi/t98m4AjQ37rTpHcy/N0rw4XnIF0AA54Jvp6Pqje/cdBV/a4j1CcDx1DoHbRSOSRdIvvtkBEE=
  on:
    tags: true
    all_branches: true
    repo: AppGyver/steroids
    condition: $(uname) = 'Linux'
